var GAME_VARS = [];
var SORPIGAL_DUNGEON_QUEST = 0;
var SORPIGAL_DUNGEON_GNASHER_DOOR = 1;
var SORPIGAL_SW_GRASS_CHEST = 2;
var SORPIGAL_WW_CHEST = 3;
var SORPIGAL_ISLAND_CHEST = 4;
var SORPIGAL_TREE_CHEST = 5;
var SORPIGAL_HOUSE_CHEST = 6;
var SORPIGAL_DUNGEON_CHEST = 7;
var SORPIGAL_DUNGEON_CHEST_2 = 8;
var SORPIGAL_DUNGEON_CHEST_3 = 9;
var SORPIGAL_DUNGEON_CHEST_4 = 10;
var SORPIGAL_DUNGEON_CHEST_5 = 11;
var SORPIGAL_DUNGEON_CHEST_6 = 12;
var SORPIGAL_DUNGEON_CHEST_7 = 13;
var SORPIGAL_TREE_CHEST_2 = 14;
var SORPIGAL_DOLL_QUEST = 15;
var A2_ALTAR = 16;
var DARK_CAVE_KEY_CHEST = 17;
var DARK_CAVE_OPENED_DOOR = 18;
var DARK_CAVE_CRYSTAL_KEY_CHEST = 19;
var DARK_CAVE_CHEST_1 = 20;
var DARK_CAVE_WW_CHEST = 21;
var DARK_CAVE_GROVE_CHEST = 22;
var DARK_CAVE_CHEST_2 = 23;
var DARK_CAVE_CHEST_3 = 24;
var DARK_CAVE_CHEST_4 = 25;
var DARK_CAVE_CHEST_5 = 26;

function setGameVar(gameVar, value) {
	GAME_VARS[gameVar] = value;
}

function getGameVar(gameVar) {
	var val = GAME_VARS[gameVar];
	
	if(val == undefined)
		return 0;
	
	return val;
}